/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionWin;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logicaNegocio.Logica;

/**
 *
 * @author EduPiry
 */
public class ListadoVista extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloComidas = new DefaultTableModel();
    private DefaultTableModel modeloClientes = new DefaultTableModel();
    private DefaultTableModel modeloIngredientes = new DefaultTableModel();
    private DefaultTableModel modeloPedidos = new DefaultTableModel();
    private DefaultTableModel modeloRecetas = new DefaultTableModel();
    private DefaultTableModel modeloSecciones = new DefaultTableModel();
    private Logica logicaTabla;
    /**
     * Creates new form ListaClienteVista
     */
    public ListadoVista(Logica logicaDatos) {
        initComponents();
        logicaTabla = logicaDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buscador1 = new javax.swing.JTextField();
        filtroComidas = new javax.swing.JRadioButton();
        filtroClientes = new javax.swing.JRadioButton();
        filtroIngredientes = new javax.swing.JRadioButton();
        filtroPedidos = new javax.swing.JRadioButton();
        filtroRecetas = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        buscador2 = new javax.swing.JTextField();
        filtroSecciones = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("LISTADO DE LOS REGISTROS");

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistros);

        jLabel2.setText("BUSCAR POR NOMBRE:");

        buscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscador1KeyReleased(evt);
            }
        });

        filtroComidas.setText("COMIDAS");

        filtroClientes.setText("CLIENTES");

        filtroIngredientes.setText("INGREDIENTES");

        filtroPedidos.setText("PEDIDOS");

        filtroRecetas.setText("RECETAS");

        jLabel3.setText("BUSCAR POR ID:");

        filtroSecciones.setText("SECCIONES");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buscador1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroComidas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroIngredientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroPedidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroRecetas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buscador2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filtroSecciones, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(409, 409, 409))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(filtroComidas)
                                .addGap(29, 29, 29)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(filtroClientes)
                                .addGap(30, 30, 30)
                                .addComponent(filtroIngredientes)
                                .addGap(28, 28, 28)
                                .addComponent(filtroPedidos)
                                .addGap(28, 28, 28)
                                .addComponent(filtroRecetas))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(buscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(buscador2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(filtroSecciones)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroComidas)
                    .addComponent(filtroClientes)
                    .addComponent(filtroIngredientes)
                    .addComponent(filtroPedidos)
                    .addComponent(filtroRecetas)
                    .addComponent(filtroSecciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscador1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscador1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador1;
    private javax.swing.JTextField buscador2;
    private javax.swing.JRadioButton filtroClientes;
    private javax.swing.JRadioButton filtroComidas;
    private javax.swing.JRadioButton filtroIngredientes;
    private javax.swing.JRadioButton filtroPedidos;
    private javax.swing.JRadioButton filtroRecetas;
    private javax.swing.JRadioButton filtroSecciones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables
    private void borrarFilas() {
        DefaultTableModel model = (DefaultTableModel) tablaRegistros.getModel();
        model.setRowCount(0); // Elimina todas las filas de la tabla
    }
    private void armarCabeceraComidas(){
        modeloComidas.setColumnCount(0);
        modeloComidas.addColumn("Nombre");
        modeloComidas.addColumn("Receta");
        modeloComidas.addColumn("Precio");
        tablaRegistros.setModel(modeloComidas);
        tablaRegistros.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    private void armarCabeceraClientes(){
        modeloClientes.setColumnCount(0);
        modeloClientes.addColumn("ID");
        modeloClientes.addColumn("Nombre");
        modeloClientes.addColumn("Direccion");
        tablaRegistros.setModel(modeloClientes);
        tablaRegistros.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(200);
    }
    private void armarCabeceraIngredientes(){
        modeloIngredientes.setColumnCount(0);
        modeloIngredientes.addColumn("Nombre");
        modeloIngredientes.addColumn("Costo");
        modeloIngredientes.addColumn("Stock");
        tablaRegistros.setModel(modeloIngredientes);
        tablaRegistros.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    private void armarCabeceraPedidos(){
        modeloPedidos.setColumnCount(0);
        modeloPedidos.addColumn("ID");
        modeloPedidos.addColumn("Comidas");
        modeloPedidos.addColumn("Precio");
        modeloPedidos.addColumn("Estado");
        tablaRegistros.setModel(modeloPedidos);
        tablaRegistros.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
    private void armarCabeceraRecetas(){
        modeloRecetas.setColumnCount(0);
        modeloRecetas.addColumn("Nombre");
        modeloRecetas.addColumn("Ingredientes");
        modeloRecetas.addColumn("Tiempo de Coccion");
        modeloRecetas.addColumn("Tipo");
        modeloRecetas.addColumn("Complejidad");
        modeloRecetas.addColumn("Recetas Dependientes");
        tablaRegistros.setModel(modeloRecetas);
        tablaRegistros.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(3).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(4).setPreferredWidth(150);
        tablaRegistros.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    private void armarCabeceraSecciones(){
        modeloSecciones.setColumnCount(0);
        modeloSecciones.addColumn(rootPane);
    }

}
