/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacionWin;

import java.util.ArrayList;
import java.util.List;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import logicaNegocio.GestionRecetas;
import logicaNegocio.Ingrediente;
import logicaNegocio.Logica;
import logicaNegocio.Receta;

/**
 *
 * @author EduPiry
 */
public class RecetaVista extends javax.swing.JInternalFrame {

    private Logica logicaRecetas;
    private List<Ingrediente> listaIngredientes;
    private List<Receta> listaRecetas;
    private GestionRecetas gestionRecetas;
    /**
     * Creates new form RecetaVista
     */
    public RecetaVista(Logica logicaDatos) {
        initComponents();
        logicaRecetas = logicaDatos;
        listaIngredientes = new ArrayList();
        listaRecetas = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botonAgregarIngredientes = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        textTiempoCoccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textComplejidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        botonAgregarRecetas = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel8.setText("REGISTRO DE RECETAS");

        jLabel9.setText("NOMBRE :");

        jLabel10.setText("LISTA DE INGREDIENTES :");

        botonAgregarIngredientes.setText("AGREGAR INGREDIENTES");
        botonAgregarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarIngredientesActionPerformed(evt);
            }
        });

        jLabel11.setText("TIEMPO DE COCCION :");

        jLabel12.setText("TIPO :");

        jLabel13.setText("COMPLEJIDAD :");

        jLabel14.setText("RECETAS DEPENDIENTES :");

        botonAgregarRecetas.setText("AGREGAR RECETAS");
        botonAgregarRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRecetasActionPerformed(evt);
            }
        });

        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonAgregarIngredientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textTiempoCoccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textComplejidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonAgregarRecetas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botonModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addGap(27, 27, 27)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textComplejidad)
                                        .addComponent(textTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textTiempoCoccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botonAgregarIngredientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addComponent(botonAgregarRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(botonGuardar)
                        .addGap(80, 80, 80)
                        .addComponent(botonModificar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(botonAgregarIngredientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textTiempoCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textComplejidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(botonAgregarRecetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonModificar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        gestionRecetas.setRecetas(logicaRecetas.loadRecetas());
        Receta receta1 = new Receta();
        receta1.setNombre(textNombre.getText());
        receta1.setIngredientes(listaIngredientes);
        receta1.setTiempoCoccion(Integer.parseInt(textTiempoCoccion.getText()));
        receta1.setTipo(textTipo.getText());
        receta1.setComplejidad(textComplejidad.getText());
        receta1.setRecetasDependientes(listaRecetas);
        gestionRecetas.agregarReceta(receta1);
        logicaRecetas.saveRecetas(gestionRecetas.getRecetas());
        
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonAgregarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarIngredientesActionPerformed
        // TODO add your handling code here:
        ListadoVista lr = new ListadoVista(logicaRecetas);
        lr.setVisible(true);
        CasaDeComidasVista.obtenerEscritorio().add(lr);
        int x = (CasaDeComidasVista.obtenerEscritorio().getWidth() - lr.getWidth()) / 2;
        int y = (CasaDeComidasVista.obtenerEscritorio().getHeight() - lr.getHeight()) / 2;
        lr.setLocation(x, y);
        CasaDeComidasVista.obtenerEscritorio().moveToFront(lr);
        lr.addInternalFrameListener(new InternalFrameListener() {
            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
                // Este método se llama cuando se abre el JInternalFrame
                lr.filtroIngredientes.setSelected(true);
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                // Este método se llama cuando se cierra el JInternalFrame
                listaIngredientes = lr.agregarIngredientes;
                
                // Realiza aquí las acciones que deseas cuando se cierra
                // por ejemplo, actualizaciones o notificaciones.
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                // Este método se llama después de que el JInternalFrame se haya cerrado
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se minimiza
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se restaura desde la minimización
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se activa (gana el foco)
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se desactiva (pierde el foco)
            }
        });
    }//GEN-LAST:event_botonAgregarIngredientesActionPerformed

    private void botonAgregarRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRecetasActionPerformed
        // TODO add your handling code here:
        ListadoVista lr = new ListadoVista(logicaRecetas);
        lr.setVisible(true);
        CasaDeComidasVista.obtenerEscritorio().add(lr);
        int x = (CasaDeComidasVista.obtenerEscritorio().getWidth() - lr.getWidth()) / 2;
        int y = (CasaDeComidasVista.obtenerEscritorio().getHeight() - lr.getHeight()) / 2;
        lr.setLocation(x, y);
        CasaDeComidasVista.obtenerEscritorio().moveToFront(lr);
        lr.addInternalFrameListener(new InternalFrameListener() {
            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
                // Este método se llama cuando se abre el JInternalFrame
                lr.filtroRecetas.setSelected(true);
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                // Este método se llama cuando se cierra el JInternalFrame
                listaRecetas = lr.agregarRecetas;
                
                // Realiza aquí las acciones que deseas cuando se cierra
                // por ejemplo, actualizaciones o notificaciones.
            }

            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                // Este método se llama después de que el JInternalFrame se haya cerrado
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se minimiza
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se restaura desde la minimización
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se activa (gana el foco)
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
                // Este método se llama cuando el JInternalFrame se desactiva (pierde el foco)
            }
        });
    }//GEN-LAST:event_botonAgregarRecetasActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        gestionRecetas.setRecetas(logicaRecetas.loadRecetas());
        Receta receta1 = new Receta();
        receta1.setNombre(textNombre.getText());
        receta1.setIngredientes(listaIngredientes);
        receta1.setTiempoCoccion(Integer.parseInt(textTiempoCoccion.getText()));
        receta1.setTipo(textTipo.getText());
        receta1.setComplejidad(textComplejidad.getText());
        receta1.setRecetasDependientes(listaRecetas);
        gestionRecetas.modificarReceta(receta1);
        logicaRecetas.saveRecetas(gestionRecetas.getRecetas());
        
    }//GEN-LAST:event_botonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarIngredientes;
    private javax.swing.JButton botonAgregarRecetas;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textComplejidad;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTiempoCoccion;
    private javax.swing.JTextField textTipo;
    // End of variables declaration//GEN-END:variables
}
